LOCATIONS = {
    { "@The World That Never Was - Dark City/(TWTNW) Fragment Crossing Mythril Stone/(TWTNW) Fragment Crossing Mythril Stone" },
    { "@The World That Never Was - Dark City/(TWTNW) Fragment Crossing Mythril Crystal/(TWTNW) Fragment Crossing Mythril Crystal" },
    { "@The World That Never Was - Dark City/(TWTNW) Fragment Crossing AP Boost/(TWTNW) Fragment Crossing AP Boost" },
    { "@The World That Never Was - Dark City/(TWTNW) Fragment Crossing Orichalcum/(TWTNW) Fragment Crossing Orichalcum" },
    { "(TWTNW) Roxas Bonus: Sora Slot 1" },
    { "(TWTNW) Roxas Bonus: Sora Slot 2" },
    { "(TWTNW) Roxas Secret Ansem Report 8" },
    { "(TWTNW) Two Become One" },
    { "@The World That Never Was - Dark City/(TWTNW) Memory's Skyscaper Mythril Crystal/(TWTNW) Memory's Skyscaper Mythril Crystal" },
    { "@The World That Never Was - Dark City/(TWTNW) Memory's Skyscaper AP Boost/(TWTNW) Memory's Skyscaper AP Boost" },
    { "@The World That Never Was - Dark City/(TWTNW) Memory's Skyscaper Mythril Stone/(TWTNW) Memory's Skyscaper Mythril Stone" },
    { "@The World That Never Was - Dark City/(TWTNW) The Brink of Despair Dark City Map/(TWTNW) The Brink of Despair Dark City Map" },
    { "@The World That Never Was - Dark City/(TWTNW) The Brink of Despair Orichalcum+/(TWTNW) The Brink of Despair Orichalcum+" },
    { "@The World That Never Was - Castle/(TWTNW) Nothing's Call Mythril Gem/(TWTNW) Nothing's Call Mythril Gem" },
    { "@The World That Never Was - Castle/(TWTNW) Nothing's Call Orichalcum/(TWTNW) Nothing's Call Orichalcum" },
    { "@The World That Never Was - Castle/(TWTNW) Twilight's View Cosmic Belt/(TWTNW) Twilight's View Cosmic Belt" },
    { "(TWTNW) Xigbar Bonus: Sora Slot 1" },
    { "(TWTNW) Xigbar Secret Ansem Report 3" },
    { "@The World That Never Was - Castle/(TWTNW) Naught's Skyway Mythril Gem/(TWTNW) Naught's Skyway Mythril Gem" },
    { "@The World That Never Was - Castle/(TWTNW) Naught's Skyway Orichalcum/(TWTNW) Naught's Skyway Orichalcum" },
    { "@The World That Never Was - Castle/(TWTNW) Naught's Skyway Mythril Crystal/(TWTNW) Naught's Skyway Mythril Crystal" },
    { "(TWTNW) Oblivion" },
    { "(TWTNW) Castle That Never Was Map" },
    { "(TWTNW) Luxord Bonus: Sora Slot 2" },
    { "(TWTNW) Luxord Bonus: Sora Slot 1" },
    { "(TWTNW) Luxord Secret Ansem Report 9" },
    { "(TWTNW) Saix Bonus: Sora Slot 1" },
    { "(TWTNW) Saix Secret Ansem Report 12" },
    { "(TWTNW) Secret Ansem Report 11 (Pre-Xemnas 1)" },
    { "@The World That Never Was - Castle/(TWTNW) Ruin and Creation's Passage Mythril Stone/(TWTNW) Ruin and Creation's Passage Mythril Stone" },
    { "@The World That Never Was - Castle/(TWTNW) Ruin and Creation's Passage AP Boost/(TWTNW) Ruin and Creation's Passage AP Boost" },
    { "@The World That Never Was - Castle/(TWTNW) Ruin and Creation's Passage Mythril Crystal/(TWTNW) Ruin and Creation's Passage Mythril Crystal" },
    { "@The World That Never Was - Castle/(TWTNW) Ruin and Creation's Passage Orichalcum/(TWTNW) Ruin and Creation's Passage Orichalcum" },
    { "(TWTNW) Xemnas 1 Bonus: Sora Slot 1" },
    { "(TWTNW) Xemnas 1 Bonus: Sora Slot 2" },
    { "(TWTNW) Xemnas 1 Secret Ansem Report 13" },
    { "Data Xemnas" },
    { "@Twilight Town/(TT) Old Mansion Potion/(TT) Old Mansion Potion" },
    { "@Twilight Town/(TT) Old Mansion Mythril Shard/(TT) Old Mansion Mythril Shard" },
    { "@Twilight Town/(TT) The Woods Potion/(TT) The Woods Potion" },
    { "@Twilight Town/(TT) The Woods Mythril Shard/(TT) The Woods Mythril Shard" },
    { "@Twilight Town/(TT) The Woods Hi-Potion/(TT) The Woods Hi-Potion" },
    { "@Twilight Town/(TT) Tram Common Hi-Potion/(TT) Tram Common Hi-Potion" },
    { "@Twilight Town/(TT) Tram Common AP Boost/(TT) Tram Common AP Boost" },
    { "@Twilight Town/(TT) Tram Common Tent/(TT) Tram Common Tent" },
    { "@Twilight Town/(TT) Tram Common Mythril Shard 1/(TT) Tram Common Mythril Shard 1" },
    { "@Twilight Town/(TT) Tram Common Potion 1/(TT) Tram Common Potion 1" },
    { "@Twilight Town/(TT) Tram Common Mythril Shard 2/(TT) Tram Common Mythril Shard 2" },
    { "@Twilight Town/(TT) Tram Common Potion 2/(TT) Tram Common Potion 2" },
    { "(TT) Station Plaza Secret Ansem Report 2" },
    { "(TT) Munny Pouch Mickey" },
    { "(TT) Crystal Orb" },
    { "@Twilight Town/(TT) Central Station Tent/(TT) Central Station Tent" },
    { "@Twilight Town/(TT) Central Station Hi-Potion/(TT) Central Station Hi-Potion" },
    { "@Twilight Town/(TT) Central Station Mythril Shard/(TT) Central Station Mythril Shard" },
    { "@Twilight Town - Tower/(TT) The Tower Potion/(TT) The Tower Potion" },
    { "@Twilight Town - Tower/(TT) The Tower Hi-Potion/(TT) The Tower Hi-Potion" },
    { "@Twilight Town - Tower/(TT) The Tower Ether/(TT) The Tower Ether" },
    { "@Twilight Town - Tower/(TT) Tower Entryway Ether/(TT) Tower Entryway Ether" },
    { "@Twilight Town - Tower/(TT) Tower Entryway Mythril Shard/(TT) Tower Entryway Mythril Shard" },
    { "@Twilight Town - Tower/(TT) Sorcerer's Loft Tower Map/(TT) Sorcerer's Loft Tower Map" },
    { "@Twilight Town - Tower/(TT) Tower Wardrobe Mythril Stone/(TT) Tower Wardrobe Mythril Stone" },
    { "(TT) Star Seeker" },
    { "(TT) Valor Form" },
    { "(TT2) Seifer's Trophy" },
    { "(TT2) Oathkeeper" },
    { "(TT2) Limit Form" },
    { "@Twilight Town Third Visit/(TT3) Underground Concourse Mythril Gem/(TT3) Underground Concourse Mythril Gem" },
    { "@Twilight Town Third Visit/(TT3) Underground Concourse AP Boost/(TT3) Underground Concourse AP Boost" },
    { "@Twilight Town Third Visit/(TT3) Underground Concourse Orichalcum/(TT3) Underground Concourse Orichalcum" },
    { "@Twilight Town Third Visit/(TT3) Underground Concourse Mythril Crystal/(TT3) Underground Concourse Mythril Crystal" },
    { "@Twilight Town Third Visit/(TT3) Tunnelway Orichalcum/(TT3) Tunnelway Orichalcum" },
    { "@Twilight Town Third Visit/(TT3) Tunnelway Mythril Crystal/(TT3) Tunnelway Mythril Crystal" },
    { "@Twilight Town Third Visit/(TT3) Sunset Terrace Orichalcum+/(TT3) Sunset Terrace Orichalcum+" },
    { "@Twilight Town Third Visit/(TT3) Sunset Terrace Mythril Shard/(TT3) Sunset Terrace Mythril Shard" },
    { "@Twilight Town Third Visit/(TT3) Sunset Terrace Mythril Crystal/(TT3) Sunset Terrace Mythril Crystal" },
    { "@Twilight Town Third Visit/(TT3) Sunset Terrace AP Boost/(TT3) Sunset Terrace AP Boost" },
    { "(TT3) Mansion Nobodies Bonus: Sora Slot 1" },
    { "@Twilight Town Third Visit/(TT3) Mansion Foyer Mythril Crystal/(TT3) Mansion Foyer Mythril Crystal" },
    { "@Twilight Town Third Visit/(TT3) Mansion Foyer Mythril Stone/(TT3) Mansion Foyer Mythril Stone" },
    { "@Twilight Town Third Visit/(TT3) Mansion Foyer Serenity Crystal/(TT3) Mansion Foyer Serenity Crystal" },
    { "@Twilight Town Third Visit/(TT3) Mansion Dining Room Mythril Crystal/(TT3) Mansion Dining Room Mythril Crystal" },
    { "@Twilight Town Third Visit/(TT3) Mansion Dining Room Mythril Stone/(TT3) Mansion Dining Room Mythril Stone" },
    { "@Twilight Town Third Visit/(TT3) Mansion Library Orichalcum/(TT3) Mansion Library Orichalcum" },
    { "(TT3) Beam Secret Ansem Report 10" },
    { "@Twilight Town Third Visit/(TT3) Mansion Basement Corridor Ultimate Recipe/(TT3) Mansion Basement Corridor Ultimate Recipe" },
    { "(TT3) Betwixt and Between" },
    { "(TT3) Betwixt and Between Bond of Flame" },
    { "Data Axel" },
    { "(STT) Twilight Town Map" },
    { "(STT) Munny Pouch Olette" },
    { "(STT) Station Dusks" },
    { "@Simulated Twilight Town/(STT) Station of Serenity Potion/(STT) Station of Serenity Potion" },
    { "@Simulated Twilight Town/(STT) Station of Calling Potion/(STT) Station of Calling Potion" },
    { "(STT) Twilight Thorn" },
    { "(STT) Axel 1" },
    { "(STT) Junk Champion Belt" },
    { "(STT) Junk Medal" },
    { "(STT) The Struggle Trophy" },
    { "@Simulated Twilight Town/(STT) Central Station Potion 1/(STT) Central Station Potion 1" },
    { "@Simulated Twilight Town/(STT) Central Station Hi-Potion/(STT) Central Station Hi-Potion" },
    { "@Simulated Twilight Town/(STT) Central Station Potion 2/(STT) Central Station Potion 2" },
    { "@Simulated Twilight Town/(STT) Sunset Terrace Ability Ring/(STT) Sunset Terrace Ability Ring" },
    { "@Simulated Twilight Town/(STT) Sunset Terrace Hi-Potion/(STT) Sunset Terrace Hi-Potion" },
    { "@Simulated Twilight Town/(STT) Sunset Terrace Potion 1/(STT) Sunset Terrace Potion 1" },
    { "@Simulated Twilight Town/(STT) Sunset Terrace Potion 2/(STT) Sunset Terrace Potion 2" },
    { "@Simulated Twilight Town/(STT) Mansion Foyer Hi-Potion/(STT) Mansion Foyer Hi-Potion" },
    { "@Simulated Twilight Town/(STT) Mansion Foyer Potion 1/(STT) Mansion Foyer Potion 1" },
    { "@Simulated Twilight Town/(STT) Mansion Foyer Potion 2/(STT) Mansion Foyer Potion 2" },
    { "@Simulated Twilight Town/(STT) Mansion Dining Room Elven Bandanna/(STT) Mansion Dining Room Elven Bandanna" },
    { "@Simulated Twilight Town/(STT) Mansion Dining Room Potion/(STT) Mansion Dining Room Potion" },
    { "(STT) Namine's Sketches" },
    { "(STT) Mansion Map" },
    { "@Simulated Twilight Town/(STT) Mansion Library Hi-Potion/(STT) Mansion Library Hi-Potion" },
    { "(STT) Axel 2" },
    { "@Simulated Twilight Town/(STT) Mansion Basement Corridor Hi-Potion/(STT) Mansion Basement Corridor Hi-Potion" },
    { "Data Roxas" },
    { "@Pride Lands/(PL) Gorge Savannah Map/(PL) Gorge Savannah Map" },
    { "@Pride Lands/(PL) Gorge Dark Gem/(PL) Gorge Dark Gem" },
    { "@Pride Lands/(PL) Gorge Mythril Stone/(PL) Gorge Mythril Stone" },
    { "@Pride Lands/(PL) Elephant Graveyard Frost Gem/(PL) Elephant Graveyard Frost Gem" },
    { "@Pride Lands/(PL) Elephant Graveyard Mythril Stone/(PL) Elephant Graveyard Mythril Stone" },
    { "@Pride Lands/(PL) Elephant Graveyard Bright Stone/(PL) Elephant Graveyard Bright Stone" },
    { "@Pride Lands/(PL) Elephant Graveyard AP Boost/(PL) Elephant Graveyard AP Boost" },
    { "@Pride Lands/(PL) Elephant Graveyard Mythril Shard/(PL) Elephant Graveyard Mythril Shard" },
    { "@Pride Lands/(PL) Pride Rock Map/(PL) Pride Rock Map" },
    { "@Pride Lands/(PL) Pride Rock Mythril Stone/(PL) Pride Rock Mythril Stone" },
    { "@Pride Lands/(PL) Pride Rock Serenity Crystal/(PL) Pride Rock Serenity Crystal" },
    { "@Pride Lands/(PL) Wildebeest Valley Energy Stone/(PL) Wildebeest Valley Energy Stone" },
    { "@Pride Lands/(PL) Wildebeest Valley AP Boost/(PL) Wildebeest Valley AP Boost" },
    { "@Pride Lands/(PL) Wildebeest Valley Mythril Gem/(PL) Wildebeest Valley Mythril Gem" },
    { "@Pride Lands/(PL) Wildebeest Valley Mythril Stone/(PL) Wildebeest Valley Mythril Stone" },
    { "@Pride Lands/(PL) Wildebeest Valley Lucid Gem/(PL) Wildebeest Valley Lucid Gem" },
    { "@Pride Lands/(PL) Wastelands Mythril Shard/(PL) Wastelands Mythril Shard" },
    { "@Pride Lands/(PL) Wastelands Serenity Gem/(PL) Wastelands Serenity Gem" },
    { "@Pride Lands/(PL) Wastelands Mythril Stone/(PL) Wastelands Mythril Stone" },
    { "@Pride Lands/(PL) Jungle Serenity Gem/(PL) Jungle Serenity Gem" },
    { "@Pride Lands/(PL) Jungle Mythril Stone/(PL) Jungle Mythril Stone" },
    { "@Pride Lands/(PL) Jungle Serenity Crystal/(PL) Jungle Serenity Crystal" },
    { "@Pride Lands/(PL) Oasis Map/(PL) Oasis Map" },
    { "@Pride Lands/(PL) Oasis Torn Pages/(PL) Oasis Torn Pages" },
    { "@Pride Lands/(PL) Oasis AP Boost/(PL) Oasis AP Boost" },
    { "(PL) Circle of Life" },
    { "(PL) Hyenas 1 Bonus: Sora Slot 1" },
    { "(PL) Scar Bonus: Sora Slot 1" },
    { "(PL) Scar Fire Element" },
    { "(PL2) Hyenas 2 Bonus: Sora Slot 1" },
    { "(PL2) Groundshaker Bonus: Sora Slot 1" },
    { "(PL2) Groundshaker Bonus: Sora Slot 2" },
    { "Data Saix" },
    { "(HB) Marketplace Map" },
    { "@Hollow Bastion/(HB) Borough Drive Recovery/(HB) Borough Drive Recovery" },
    { "@Hollow Bastion/(HB) Borough AP Boost/(HB) Borough AP Boost" },
    { "@Hollow Bastion/(HB) Borough Hi-Potion/(HB) Borough Hi-Potion" },
    { "@Hollow Bastion/(HB) Borough Mythril Shard/(HB) Borough Mythril Shard" },
    { "@Hollow Bastion/(HB) Borough Dark Shard/(HB) Borough Dark Shard" },
    { "(HB) Merlin's House Membership Card" },
    { "(HB) Merlin's House Blizzard Element" },
    { "(HB) Bailey Bonus: Sora Slot 1" },
    { "(HB) Bailey Secret Ansem Report 7" },
    { "(HB) Baseball Charm" },
    { "@Hollow Bastion Second Visit/(HB2) Postern Castle Perimeter Map/(HB2) Postern Castle Perimeter Map" },
    { "@Hollow Bastion Second Visit/(HB2) Postern Mythril Gem/(HB2) Postern Mythril Gem" },
    { "@Hollow Bastion Second Visit/(HB2) Postern AP Boost/(HB2) Postern AP Boost" },
    { "@Hollow Bastion Second Visit/(HB2) Corridors Mythril Stone/(HB2) Corridors Mythril Stone" },
    { "@Hollow Bastion Second Visit/(HB2) Corridors Mythril Crystal/(HB2) Corridors Mythril Crystal" },
    { "@Hollow Bastion Second Visit/(HB2) Corridors Dark Crystal/(HB2) Corridors Dark Crystal" },
    { "@Hollow Bastion Second Visit/(HB2) Corridors AP Boost/(HB2) Corridors AP Boost" },
    { "(HB2) Ansem's Study Master Form" },
    { "(HB2) Ansem's Study Sleeping Lion" },
    { "@Hollow Bastion Second Visit/(HB2) Ansem's Study Skill Recipe/(HB2) Ansem's Study Skill Recipe" },
    { "@Hollow Bastion Second Visit/(HB2) Ansem's Study Ukulele Charm/(HB2) Ansem's Study Ukulele Charm" },
    { "@Hollow Bastion Second Visit/(HB2) Restoration Site Moon Recipe/(HB2) Restoration Site Moon Recipe" },
    { "@Hollow Bastion Second Visit/(HB2) Restoration Site AP Boost/(HB2) Restoration Site AP Boost" },
    { "(HB2) Demyx Bonus: Sora Slot 1" },
    { "(HB2) Demyx Bonus: Sora Slot 2" },
    { "(HB2) FF Fights Cure Element" },
    { "@Hollow Bastion Second Visit/(HB2) Crystal Fissure Torn Pages/(HB2) Crystal Fissure Torn Pages" },
    { "@Hollow Bastion Second Visit/(HB2) Crystal Fissure The Great Maw Map/(HB2) Crystal Fissure The Great Maw Map" },
    { "@Hollow Bastion Second Visit/(HB2) Crystal Fissure Energy Crystal/(HB2) Crystal Fissure Energy Crystal" },
    { "@Hollow Bastion Second Visit/(HB2) Crystal Fissure AP Boost/(HB2) Crystal Fissure AP Boost" },
    { "(HB2) 1000 Heartless" },
    { "(HB2) 1000 Heartless Secret Ansem Report 1" },
    { "(HB2) 1000 Heartless Ice Cream" },
    { "(HB2) 1000 Heartless Picture" },
    { "@Hollow Bastion Second Visit/(HB2) Postern Gull Wing/(HB2) Postern Gull Wing" },
    { "@Hollow Bastion Second Visit/(HB2) Heartless Manufactory Cosmic Chain/(HB2) Heartless Manufactory Cosmic Chain" },
    { "Sephiroth Bonus: Sora Slot 1" },
    { "Sephiroth Fenrir" },
    { "(HB2) Winner's Proof" },
    { "(HB2) Proof of Peace" },
    { "Data Demyx" },
    { "@Hollow Bastion - Cavern of Remembrance/(CoR) Depths AP Boost/(CoR) Depths AP Boost" },
    { "@Hollow Bastion - Cavern of Remembrance/(CoR) Depths Power Crystal/(CoR) Depths Power Crystal" },
    { "@Hollow Bastion - Cavern of Remembrance/(CoR) Depths Frost Crystal/(CoR) Depths Frost Crystal" },
    { "@Hollow Bastion - Cavern of Remembrance/(CoR) Depths Manifest Illusion/(CoR) Depths Manifest Illusion" },
    { "@Hollow Bastion - Cavern of Remembrance/(CoR) Depths AP Boost 2/(CoR) Depths AP Boost 2" },
    { "@Hollow Bastion - Cavern of Remembrance/(CoR) Mineshaft Lower Level Depths of Remembrance Map/(CoR) Mineshaft Lower Level Depths of Remembrance Map" },
    { "@Hollow Bastion - Cavern of Remembrance/(CoR) Mineshaft Lower Level AP Boost/(CoR) Mineshaft Lower Level AP Boost" },
    { "@Hollow Bastion - Cavern of Remembrance/(CoR) Depths Upper Level Remembrance Gem/(CoR) Depths Upper Level Remembrance Gem" },
    { "@Hollow Bastion - Cavern of Remembrance/(CoR) Mining Area Serenity Gem/(CoR) Mining Area Serenity Gem" },
    { "@Hollow Bastion - Cavern of Remembrance/(CoR) Mining Area AP Boost/(CoR) Mining Area AP Boost" },
    { "@Hollow Bastion - Cavern of Remembrance/(CoR) Mining Area Serenity Crystal/(CoR) Mining Area Serenity Crystal" },
    { "@Hollow Bastion - Cavern of Remembrance/(CoR) Mining Area Manifest Illusion/(CoR) Mining Area Manifest Illusion" },
    { "@Hollow Bastion - Cavern of Remembrance/(CoR) Mining Area Serenity Gem 2/(CoR) Mining Area Serenity Gem 2" },
    { "@Hollow Bastion - Cavern of Remembrance/(CoR) Mining Area Dark Remembrance Map/(CoR) Mining Area Dark Remembrance Map" },
    { "@Hollow Bastion - Cavern of Remembrance/(CoR) Mineshaft Mid Level Power Boost/(CoR) Mineshaft Mid Level Power Boost" },
    { "@Hollow Bastion - Cavern of Remembrance/(CoR) Engine Chamber Serenity Crystal/(CoR) Engine Chamber Serenity Crystal" },
    { "@Hollow Bastion - Cavern of Remembrance/(CoR) Engine Chamber Remembrance Crystal/(CoR) Engine Chamber Remembrance Crystal" },
    { "@Hollow Bastion - Cavern of Remembrance/(CoR) Engine Chamber AP Boost/(CoR) Engine Chamber AP Boost" },
    { "@Hollow Bastion - Cavern of Remembrance/(CoR) Engine Chamber Manifest Illusion/(CoR) Engine Chamber Manifest Illusion" },
    { "@Hollow Bastion - Cavern of Remembrance/(CoR) Mineshaft Upper Level Magic Boost/(CoR) Mineshaft Upper Level Magic Boost" },
    { "@Hollow Bastion - Cavern of Remembrance/(CoR) Mineshaft Upper Level AP Boost/(CoR) Mineshaft Upper Level AP Boost" },
    { "Transport to Remembrance" },
    { "@Halloween Town/(HT) Graveyard Mythril Shard/(HT) Graveyard Mythril Shard" },
    { "@Halloween Town/(HT) Graveyard Serenity Gem/(HT) Graveyard Serenity Gem" },
    { "@Halloween Town/(HT) Finklestein's Lab Halloween Town Map/(HT) Finklestein's Lab Halloween Town Map" },
    { "@Halloween Town/(HT) Town Square Mythril Stone/(HT) Town Square Mythril Stone" },
    { "@Halloween Town/(HT) Town Square Energy Shard/(HT) Town Square Energy Shard" },
    { "@Halloween Town/(HT) Hinterlands Lightning Shard/(HT) Hinterlands Lightning Shard" },
    { "@Halloween Town/(HT) Hinterlands Mythril Stone/(HT) Hinterlands Mythril Stone" },
    { "@Halloween Town/(HT) Hinterlands AP Boost/(HT) Hinterlands AP Boost" },
    { "@Halloween Town/(HT) Candy Cane Lane Mega-Potion/(HT) Candy Cane Lane Mega-Potion" },
    { "@Halloween Town/(HT) Candy Cane Lane Mythril Gem/(HT) Candy Cane Lane Mythril Gem" },
    { "@Halloween Town/(HT) Candy Cane Lane Lightning Stone/(HT) Candy Cane Lane Lightning Stone" },
    { "@Halloween Town/(HT) Candy Cane Lane Mythril Stone/(HT) Candy Cane Lane Mythril Stone" },
    { "@Halloween Town/(HT) Santa's House Christmas Town Map/(HT) Santa's House Christmas Town Map" },
    { "@Halloween Town/(HT) Santa's House AP Boost/(HT) Santa's House AP Boost" },
    { "(HT) Prison Keeper Bonus: Sora Slot 1" },
    { "(HT) Oogie Boogie Bonus: Sora Slot 1" },
    { "(HT) Oogie Boogie Magnet Element" },
    { "(HT2) Lock, Shock and Barrel Bonus: Sora Slot 1" },
    { "(HT2) Present" },
    { "(HT2) Decoy Presents" },
    { "(HT2) Experiment Bonus: Sora Slot 1" },
    { "(HT2) Decisive Pumpkin" },
    { "Vexen Bonus: Sora Slot 1" },
    { "AS Vexen" },
    { "Data Vexen" },
    { "@Port Royal/(PR) Rampart Naval Map/(PR) Rampart Naval Map" },
    { "@Port Royal/(PR) Rampart Mythril Stone/(PR) Rampart Mythril Stone" },
    { "@Port Royal/(PR) Rampart Dark Shard/(PR) Rampart Dark Shard" },
    { "@Port Royal/(PR) Town Dark Stone/(PR) Town Dark Stone" },
    { "@Port Royal/(PR) Town AP Boost/(PR) Town AP Boost" },
    { "@Port Royal/(PR) Town Mythril Shard/(PR) Town Mythril Shard" },
    { "@Port Royal/(PR) Town Mythril Gem/(PR) Town Mythril Gem" },
    { "@Port Royal/(PR) Cave Mouth Bright Shard/(PR) Cave Mouth Bright Shard" },
    { "@Port Royal/(PR) Cave Mouth Mythril Shard/(PR) Cave Mouth Mythril Shard" },
    { "(PR) Isla de Muerta Map" },
    { "(PR) Boat Fight Bonus: Sora Slot 1" },
    { "(PR) Interceptor Barrels Bonus: Sora Slot 1" },
    { "@Port Royal/(PR) Powder Store AP Boost 1/(PR) Powder Store AP Boost 1" },
    { "@Port Royal/(PR) Powder Store AP Boost 2/(PR) Powder Store AP Boost 2" },
    { "@Port Royal/(PR) Moonlight Nook Mythril Shard/(PR) Moonlight Nook Mythril Shard" },
    { "@Port Royal/(PR) Moonlight Nook Serenity Gem/(PR) Moonlight Nook Serenity Gem" },
    { "@Port Royal/(PR) Moonlight Nook Power Stone/(PR) Moonlight Nook Power Stone" },
    { "(PR) Barbossa Bonus: Sora Slot 1" },
    { "(PR) Barbossa Bonus: Sora Slot 2" },
    { "(PR) Follow the Wind" },
    { "(PR2) Grim Reaper 1 Bonus: Sora Slot 1" },
    { "@Port Royal Second Visit/(PR2) Interceptor's Hold Feather Charm/(PR2) Interceptor's Hold Feather Charm" },
    { "@Port Royal Second Visit/(PR2) Seadrift Keep AP Boost/(PR2) Seadrift Keep AP Boost" },
    { "@Port Royal Second Visit/(PR2) Seadrift Keep Orichalcum/(PR2) Seadrift Keep Orichalcum" },
    { "@Port Royal Second Visit/(PR2) Seadrift Keep Meteor Staff/(PR2) Seadrift Keep Meteor Staff" },
    { "@Port Royal Second Visit/(PR2) Seadrift Row Serenity Gem/(PR2) Seadrift Row Serenity Gem" },
    { "@Port Royal Second Visit/(PR2) Seadrift Row King Recipe/(PR2) Seadrift Row King Recipe" },
    { "@Port Royal Second Visit/(PR2) Seadrift Row Mythril Crystal/(PR2) Seadrift Row Mythril Crystal" },
    { "(PR2) Seadrift Row Cursed Medallion" },
    { "(PR2) Seadrift Row Ship Graveyard Map" },
    { "(PR2) Grim Reaper 2 Bonus: Sora Slot 1" },
    { "(PR2) Secret Ansem Report 6 (Grim Reaper 2)" },
    { "Data Luxord" },
    { "@Space Paranoids/(SP) Pit Cell Area Map/(SP) Pit Cell Area Map" },
    { "@Space Paranoids/(SP) Pit Cell Mythril Crystal/(SP) Pit Cell Mythril Crystal" },
    { "@Space Paranoids/(SP) Canyon Dark Crystal/(SP) Canyon Dark Crystal" },
    { "@Space Paranoids/(SP) Canyon Mythril Stone/(SP) Canyon Mythril Stone" },
    { "@Space Paranoids/(SP) Canyon Mythril Gem/(SP) Canyon Mythril Gem" },
    { "@Space Paranoids/(SP) Canyon Frost Crystal/(SP) Canyon Frost Crystal" },
    { "(SP) Screens Bonus: Sora Slot 1" },
    { "@Space Paranoids/(SP) Hallway Power Crystal/(SP) Hallway Power Crystal" },
    { "@Space Paranoids/(SP) Hallway AP Boost/(SP) Hallway AP Boost" },
    { "@Space Paranoids/(SP) Communications Room I/O Tower Map/(SP) Communications Room I/O Tower Map" },
    { "@Space Paranoids/(SP) Communications Room Gaia Belt/(SP) Communications Room Gaia Belt" },
    { "(SP) Hostile Program Bonus: Sora Slot 1" },
    { "(SP) Hostile Program Bonus: Sora Slot 2" },
    { "(SP) Photon Debugger" },
    { "(SP2) Solar Sailer" },
    { "@Space Paranoids Second Visit/(SP2) Central Computer Core AP Boost/(SP2) Central Computer Core AP Boost" },
    { "@Space Paranoids Second Visit/(SP2) Central Computer Core Orichalcum+/(SP2) Central Computer Core Orichalcum+" },
    { "@Space Paranoids Second Visit/(SP2) Central Computer Core Cosmic Arts/(SP2) Central Computer Core Cosmic Arts" },
    { "@Space Paranoids Second Visit/(SP2) Central Computer Core Map/(SP2) Central Computer Core Map" },
    { "(SP2) MCP Bonus: Sora Slot 1" },
    { "(SP2) MCP Bonus: Sora Slot 2" },
    { "Larxene Bonus: Sora Slot 1" },
    { "AS Larxene" },
    { "Data Larxene" },
    { "@Beasts Castle/(BC) Courtyard AP Boost/(BC) Courtyard AP Boost" },
    { "@Beasts Castle/(BC) Courtyard Hi-Potion/(BC) Courtyard Hi-Potion" },
    { "@Beasts Castle/(BC) Courtyard Mythril Shard/(BC) Courtyard Mythril Shard" },
    { "@Beasts Castle/(BC) Belle's Room Castle Map/(BC) Belle's Room Castle Map" },
    { "@Beasts Castle/(BC) Belle's Room Mega-Recipe/(BC) Belle's Room Mega-Recipe" },
    { "@Beasts Castle/(BC) The East Wing Mythril Shard/(BC) The East Wing Mythril Shard" },
    { "@Beasts Castle/(BC) The East Wing Tent/(BC) The East Wing Tent" },
    { "@Beasts Castle/(BC) The West Hall Hi-Potion/(BC) The West Hall Hi-Potion" },
    { "@Beasts Castle/(BC) The West Hall Power Shard/(BC) The West Hall Power Shard" },
    { "@Beasts Castle/(BC) The West Hall AP Boost Post Dungeon/(BC) The West Hall AP Boost Post Dungeon" },
    { "@Beasts Castle/(BC) The West Hall Bright Stone/(BC) The West Hall Bright Stone" },
    { "@Beasts Castle/(BC) The West Hall Mythril Shard/(BC) The West Hall Mythril Shard" },
    { "(BC) Thresholder Bonus: Sora Slot 1" },
    { "@Beasts Castle/(BC) Dungeon Basement Map/(BC) Dungeon Basement Map" },
    { "@Beasts Castle/(BC) Dungeon AP Boost/(BC) Dungeon AP Boost" },
    { "@Beasts Castle/(BC) Secret Passage Mythril Shard/(BC) Secret Passage Mythril Shard" },
    { "@Beasts Castle/(BC) Secret Passage Hi-Potion/(BC) Secret Passage Hi-Potion" },
    { "@Beasts Castle/(BC) Secret Passage Lucid Shard/(BC) Secret Passage Lucid Shard" },
    { "@Beasts Castle/(BC) The West Hall Mythril Shard 2/(BC) The West Hall Mythril Shard 2" },
    { "@Beasts Castle/(BC) The West Wing Mythril Shard/(BC) The West Wing Mythril Shard" },
    { "@Beasts Castle/(BC) The West Wing Tent/(BC) The West Wing Tent" },
    { "(BC) Beast Bonus: Sora Slot 1" },
    { "@Beasts Castle/(BC) The Beast's Room Blazing Shard/(BC) The Beast's Room Blazing Shard" },
    { "(BC) Dark Thorn Bonus: Sora Slot 1" },
    { "(BC) Dark Thorn Bonus: Sora Slot 2" },
    { "(BC) Dark Thorn Cure Element" },
    { "(BC2) Rumbling Rose" },
    { "(BC2) Castle Walls Map" },
    { "(BC2) Xaldin Bonus: Sora Slot 1" },
    { "(BC2) Xaldin Bonus: Sora Slot 2" },
    { "(BC2) Secret Ansem Report 4 (Xaldin)" },
    { "Data Xaldin" },
    { "@Olympus Coliseum/(OC) Passage Mythril Shard/(OC) Passage Mythril Shard" },
    { "@Olympus Coliseum/(OC) Passage Mythril Stone/(OC) Passage Mythril Stone" },
    { "@Olympus Coliseum/(OC) Passage Ether/(OC) Passage Ether" },
    { "@Olympus Coliseum/(OC) Passage AP Boost/(OC) Passage AP Boost" },
    { "@Olympus Coliseum/(OC) Passage Hi-Potion/(OC) Passage Hi-Potion" },
    { "@Olympus Coliseum/(OC) Inner Chamber Underworld Map/(OC) Inner Chamber Underworld Map" },
    { "@Olympus Coliseum/(OC) Inner Chamber Mythril Shard/(OC) Inner Chamber Mythril Shard" },
    { "(OC) Cerberus Bonus: Sora Slot 1" },
    { "(OC) Coliseum Map" },
    { "(OC) Urns Bonus: Sora Slot 1" },
    { "@Olympus Coliseum/(OC) Underworld Entrance Power Boost/(OC) Underworld Entrance Power Boost" },
    { "@Olympus Coliseum/(OC) Caverns Entrance Lucid Shard/(OC) Caverns Entrance Lucid Shard" },
    { "@Olympus Coliseum/(OC) Caverns Entrance AP Boost/(OC) Caverns Entrance AP Boost" },
    { "@Olympus Coliseum/(OC) Caverns Entrance Mythril Shard/(OC) Caverns Entrance Mythril Shard" },
    { "@Olympus Coliseum/(OC) The Lost Road Bright Shard/(OC) The Lost Road Bright Shard" },
    { "@Olympus Coliseum/(OC) The Lost Road Ether/(OC) The Lost Road Ether" },
    { "@Olympus Coliseum/(OC) The Lost Road Mythril Shard/(OC) The Lost Road Mythril Shard" },
    { "@Olympus Coliseum/(OC) The Lost Road Mythril Stone/(OC) The Lost Road Mythril Stone" },
    { "@Olympus Coliseum/(OC) Atrium Lucid Stone/(OC) Atrium Lucid Stone" },
    { "@Olympus Coliseum/(OC) Atrium AP Boost/(OC) Atrium AP Boost" },
    { "(OC) Demyx Bonus: Sora Slot 1" },
    { "(OC) Secret Ansem Report 5 (Demyx)" },
    { "(OC) Olympus Stone" },
    { "@Olympus Coliseum/(OC) The Lock Caverns Map/(OC) The Lock Caverns Map" },
    { "@Olympus Coliseum/(OC) The Lock Mythril Shard/(OC) The Lock Mythril Shard" },
    { "@Olympus Coliseum/(OC) The Lock AP Boost/(OC) The Lock AP Boost" },
    { "(OC) Pete OC Bonus: Sora Slot 1" },
    { "(OC) Hydra Bonus: Sora Slot 1" },
    { "(OC) Hydra Bonus: Sora Slot 2" },
    { "(OC) Hero's Crest" },
    { "(OC2) Auron's Statue" },
    { "(OC2) Hades Bonus: Sora Slot 1" },
    { "(OC2) Hades Bonus: Sora Slot 2" },
    { "(OC2) Guardian Soul" },
    { "Zexion Bonus: Sora Slot 1" },
    { "AS Zexion" },
    { "Data Zexion" },
    { "Protect Belt Pain and Panic Cup" },
    { "Serenity Gem Pain and Panic Cup" },
    { "Rising Dragon Cerberus Cup" },
    { "Serenity Crystal Cerberus Cup" },
    { "Genji Shield Titan Cup" },
    { "Skillful Ring Titan Cup" },
    { "Fatal Crest Goddess of Fate Cup" },
    { "Orichalcum+ Goddess of Fate Cup" },
    { "Hades Cup Trophy Paradox Cups" },
    { "@100 Acre Wood/(100Acre) Pooh's House 100 Acre Wood Map/(100Acre) Pooh's House 100 Acre Wood Map" },
    { "@100 Acre Wood/(100Acre) Pooh's House AP Boost/(100Acre) Pooh's House AP Boost" },
    { "@100 Acre Wood/(100Acre) Pooh's House Mythril Stone/(100Acre) Pooh's House Mythril Stone" },
    { "@100 Acre Wood 2nd Visit/(100Acre) Piglet's House Defense Boost/(100Acre) Piglet's House Defense Boost" },
    { "@100 Acre Wood 2nd Visit/(100Acre) Piglet's House AP Boost/(100Acre) Piglet's House AP Boost" },
    { "@100 Acre Wood 2nd Visit/(100Acre) Piglet's House Mythril Gem/(100Acre) Piglet's House Mythril Gem" },
    { "@100 Acre Wood 3rd Visit/(100Acre) Rabbit's House Draw Ring/(100Acre) Rabbit's House Draw Ring" },
    { "@100 Acre Wood 3rd Visit/(100Acre) Rabbit's House Mythril Crystal/(100Acre) Rabbit's House Mythril Crystal" },
    { "@100 Acre Wood 3rd Visit/(100Acre) Rabbit's House AP Boost/(100Acre) Rabbit's House AP Boost" },
    { "@100 Acre Wood 4th Visit/(100Acre) Kanga's House Magic Boost/(100Acre) Kanga's House Magic Boost" },
    { "@100 Acre Wood 4th Visit/(100Acre) Kanga's House AP Boost/(100Acre) Kanga's House AP Boost" },
    { "@100 Acre Wood 4th Visit/(100Acre) Kanga's House Orichalcum/(100Acre) Kanga's House Orichalcum" },
    { "@100 Acre Wood 5th Visit/(100Acre) Spooky Cave Mythril Gem/(100Acre) Spooky Cave Mythril Gem" },
    { "@100 Acre Wood 5th Visit/(100Acre) Spooky Cave AP Boost/(100Acre) Spooky Cave AP Boost" },
    { "@100 Acre Wood 5th Visit/(100Acre) Spooky Cave Orichalcum/(100Acre) Spooky Cave Orichalcum" },
    { "@100 Acre Wood 5th Visit/(100Acre) Spooky Cave Guard Recipe/(100Acre) Spooky Cave Guard Recipe" },
    { "@100 Acre Wood 5th Visit/(100Acre) Spooky Cave Mythril Crystal/(100Acre) Spooky Cave Mythril Crystal" },
    { "@100 Acre Wood 5th Visit/(100Acre) Spooky Cave AP Boost 2/(100Acre) Spooky Cave AP Boost 2" },
    { "@100 Acre Wood 5th Visit/(100Acre) Sweet Memories/(100Acre) Sweet Memories" },
    { "@100 Acre Wood 5th Visit/(100Acre) Spooky Cave Map/(100Acre) Spooky Cave Map" },
    { "@100 Acre Wood 5th Visit/(100Acre) Starry Hill Cosmic Ring/(100Acre) Starry Hill Cosmic Ring" },
    { "@100 Acre Wood 5th Visit/(100Acre) Starry Hill Style Recipe/(100Acre) Starry Hill Style Recipe" },
    { "@100 Acre Wood 5th Visit/(100Acre) Starry Hill Cure Element/(100Acre) Starry Hill Cure Element" },
    { "@100 Acre Wood 5th Visit/(100Acre) Starry Hill Orichalcum+/(100Acre) Starry Hill Orichalcum+" },
    { "@Disney Castle/(DC) Courtyard Mythril Shard/(DC) Courtyard Mythril Shard" },
    { "@Disney Castle/(DC) Courtyard Star Recipe/(DC) Courtyard Star Recipe" },
    { "@Disney Castle/(DC) Courtyard AP Boost/(DC) Courtyard AP Boost" },
    { "@Disney Castle/(DC) Courtyard Mythril Stone/(DC) Courtyard Mythril Stone" },
    { "@Disney Castle/(DC) Courtyard Blazing Stone/(DC) Courtyard Blazing Stone" },
    { "@Disney Castle/(DC) Courtyard Blazing Shard/(DC) Courtyard Blazing Shard" },
    { "@Disney Castle/(DC) Courtyard Mythril Shard 2/(DC) Courtyard Mythril Shard 2" },
    { "@Disney Castle/(DC) Library Torn Pages/(DC) Library Torn Pages" },
    { "(DC) Disney Castle Map" },
    { "(DC) Minnie Escort Bonus: Sora Slot 1" },
    { "(DC) Minnie Escort Bonus: Sora Slot 2" },
    { "@Timeless River/(TR) Cornerstone Hill Map/(TR) Cornerstone Hill Map" },
    { "@Timeless River/(TR) Cornerstone Hill Frost Shard/(TR) Cornerstone Hill Frost Shard" },
    { "@Timeless River/(TR) Pier Mythril Shard/(TR) Pier Mythril Shard" },
    { "@Timeless River/(TR) Pier Hi-Potion/(TR) Pier Hi-Potion" },
    { "@Timeless River/(TR) Waterway Mythril Stone/(TR) Waterway Mythril Stone" },
    { "@Timeless River/(TR) Waterway AP Boost/(TR) Waterway AP Boost" },
    { "@Timeless River/(TR) Waterway Frost Stone/(TR) Waterway Frost Stone" },
    { "(TR) Window of Time Map" },
    { "(TR) Boat Pete Bonus: Sora Slot 1" },
    { "(TR) Future Pete Bonus: Sora Slot 1" },
    { "(TR) Future Pete Bonus: Sora Slot 2" },
    { "(TR) Monochrome" },
    { "(TR) Wisdom Form" },
    { "Marluxia Bonus: Sora Slot 1" },
    { "AS Marluxia" },
    { "Data Marluxia" },
    { "Lingering Will Bonus: Sora Slot 1" },
    { "Lingering Will Proof of Connection" },
    { "Lingering Will Manifest Illusion" },
    { "(AG) Agrabah Map" },
    { "@Agraba/(AG) Agrabah Dark Shard/(AG) Agrabah Dark Shard" },
    { "@Agraba/(AG) Agrabah Mythril Shard/(AG) Agrabah Mythril Shard" },
    { "@Agraba/(AG) Agrabah Hi-Potion/(AG) Agrabah Hi-Potion" },
    { "@Agraba/(AG) Agrabah AP Boost/(AG) Agrabah AP Boost" },
    { "@Agraba/(AG) Agrabah Mythril Stone/(AG) Agrabah Mythril Stone" },
    { "@Agraba/(AG) Agrabah Mythril Shard 2/(AG) Agrabah Mythril Shard 2" },
    { "@Agraba/(AG) Agrabah Serenity Shard/(AG) Agrabah Serenity Shard" },
    { "@Agraba/(AG) Bazaar Mythril Gem/(AG) Bazaar Mythril Gem" },
    { "@Agraba/(AG) Bazaar Power Shard/(AG) Bazaar Power Shard" },
    { "@Agraba/(AG) Bazaar Hi-Potion/(AG) Bazaar Hi-Potion" },
    { "@Agraba/(AG) Bazaar AP Boost/(AG) Bazaar AP Boost" },
    { "@Agraba/(AG) Bazaar Mythril Shard/(AG) Bazaar Mythril Shard" },
    { "@Agraba/(AG) Palace Walls Skill Ring/(AG) Palace Walls Skill Ring" },
    { "@Agraba/(AG) Palace Walls Mythril Stone/(AG) Palace Walls Mythril Stone" },
    { "@Agraba/(AG) Cave Entrance Power Stone/(AG) Cave Entrance Power Stone" },
    { "@Agraba/(AG) Cave Entrance Mythril Shard/(AG) Cave Entrance Mythril Shard" },
    { "@Agraba/(AG) Valley of Stone Mythril Stone/(AG) Valley of Stone Mythril Stone" },
    { "@Agraba/(AG) Valley of Stone AP Boost/(AG) Valley of Stone AP Boost" },
    { "@Agraba/(AG) Valley of Stone Mythril Shard/(AG) Valley of Stone Mythril Shard" },
    { "@Agraba/(AG) Valley of Stone Hi-Potion/(AG) Valley of Stone Hi-Potion" },
    { "@Agraba/(AG) Abu Escort Bonus: Sora Slot 1/(AG) Abu Escort Bonus: Sora Slot 1" },
    { "@Agraba/(AG) Chasm of Challenges Cave of Wonders Map/(AG) Chasm of Challenges Cave of Wonders Map" },
    { "@Agraba/(AG) Chasm of Challenges AP Boost/(AG) Chasm of Challenges AP Boost" },
    { "@Agraba/(AG) Treasure Room/(AG) Treasure Room" },
    { "@Agraba/(AG) Treasure Room AP Boost/(AG) Treasure Room AP Boost" },
    { "@Agraba/(AG) Treasure Room Serenity Gem/(AG) Treasure Room Serenity Gem" },
    { "(AG) Elemental Lords Bonus: Sora Slot 1" },
    { "(AG) Lamp Charm" },
    { "@Agraba Second Visit/(AG2) Ruined Chamber Torn Pages/(AG2) Ruined Chamber Torn Pages" },
    { "@Agraba Second Visit/(AG2) Ruined Chamber Ruins Map/(AG2) Ruined Chamber Ruins Map" },
    { "(AG2) Genie Jafar" },
    { "(AG2) Wishing Lamp" },
    { "Lexaeus Bonus: Sora Slot 1" },
    { "AS Lexaeus" },
    { "Data Lexaeus" },
    { "@Land of Dragons/(LoD) Bamboo Grove Dark Shard/(LoD) Bamboo Grove Dark Shard" },
    { "@Land of Dragons/(LoD) Bamboo Grove Ether/(LoD) Bamboo Grove Ether" },
    { "@Land of Dragons/(LoD) Bamboo Grove Mythril Shard/(LoD) Bamboo Grove Mythril Shard" },
    { "(LoD) Bamboo Grove Encampment Area Map" },
    { "(LoD) Mission 3" },
    { "@Land of Dragons/(LoD) Checkpoint Hi-Potion/(LoD) Checkpoint Hi-Potion" },
    { "@Land of Dragons/(LoD) Checkpoint Mythril Shard/(LoD) Checkpoint Mythril Shard" },
    { "@Land of Dragons/(LoD) Mountain Trail Lightning Shard/(LoD) Mountain Trail Lightning Shard" },
    { "@Land of Dragons/(LoD) Mountain Trail Recovery Recipe/(LoD) Mountain Trail Recovery Recipe" },
    { "@Land of Dragons/(LoD) Mountain Trail Ether/(LoD) Mountain Trail Ether" },
    { "@Land of Dragons/(LoD) Mountain Trail Mythril Shard/(LoD) Mountain Trail Mythril Shard" },
    { "(LoD) Village Cave Area Map" },
    { "@Land of Dragons/(LoD) Village Cave Dark Shard/(LoD) Village Cave Dark Shard" },
    { "@Land of Dragons/(LoD) Village Cave AP Boost/(LoD) Village Cave AP Boost" },
    { "(LoD) Village Cave Bonus: Sora Slot 1" },
    { "@Land of Dragons/(LoD) Ridge Frost Shard/(LoD) Ridge Frost Shard" },
    { "@Land of Dragons/(LoD) Ridge AP Boost/(LoD) Ridge AP Boost" },
    { "(LoD) Shan-Yu Bonus: Sora Slot 1" },
    { "(LoD) Shan-Yu Bonus: Sora Slot 2" },
    { "(LoD) Hidden Dragon" },
    { "@Land of Dragons Second Visit/(LoD2) Throne Room Torn Pages/(LoD2) Throne Room Torn Pages" },
    { "@Land of Dragons Second Visit/(LoD2) Throne Room Palace Map/(LoD2) Throne Room Palace Map" },
    { "@Land of Dragons Second Visit/(LoD2) Throne Room AP Boost/(LoD2) Throne Room AP Boost" },
    { "@Land of Dragons Second Visit/(LoD2) Throne Room Queen Recipe/(LoD2) Throne Room Queen Recipe" },
    { "@Land of Dragons Second Visit/(LoD2) Throne Room AP Boost 2/(LoD2) Throne Room AP Boost 2" },
    { "@Land of Dragons Second Visit/(LoD2) Throne Room Ogre Shield/(LoD2) Throne Room Ogre Shield" },
    { "@Land of Dragons Second Visit/(LoD2) Throne Room Mythril Crystal/(LoD2) Throne Room Mythril Crystal" },
    { "@Land of Dragons Second Visit/(LoD2) Throne Room Orichalcum/(LoD2) Throne Room Orichalcum" },
    { "(LoD2) Storm Rider Bonus: Sora Slot 1" },
    { "Data Xigbar" },
    { "Level 02" },
    { "Level 03" },
    { "Level 04" },
    { "Level 05" },
    { "Level 06" },
    { "Level 07" },
    { "Level 08" },
    { "Level 09" },
    { "Level 10" },
    { "Level 11" },
    { "Level 12" },
    { "Level 13" },
    { "Level 14" },
    { "Level 15" },
    { "Level 16" },
    { "Level 17" },
    { "Level 18" },
    { "Level 19" },
    { "Level 20" },
    { "Level 21" },
    { "Level 22" },
    { "Level 23" },
    { "Level 24" },
    { "Level 25" },
    { "Level 26" },
    { "Level 27" },
    { "Level 28" },
    { "Level 29" },
    { "Level 30" },
    { "Level 31" },
    { "Level 32" },
    { "Level 33" },
    { "Level 34" },
    { "Level 35" },
    { "Level 36" },
    { "Level 37" },
    { "Level 38" },
    { "Level 39" },
    { "Level 40" },
    { "Level 41" },
    { "Level 42" },
    { "Level 43" },
    { "Level 44" },
    { "Level 45" },
    { "Level 46" },
    { "Level 47" },
    { "Level 48" },
    { "Level 49" },
    { "Level 50" },
    { "Level 51" },
    { "Level 52" },
    { "Level 53" },
    { "Level 54" },
    { "Level 55" },
    { "Level 56" },
    { "Level 57" },
    { "Level 58" },
    { "Level 59" },
    { "Level 60" },
    { "Level 61" },
    { "Level 62" },
    { "Level 63" },
    { "Level 64" },
    { "Level 65" },
    { "Level 66" },
    { "Level 67" },
    { "Level 68" },
    { "Level 69" },
    { "Level 70" },
    { "Level 71" },
    { "Level 72" },
    { "Level 73" },
    { "Level 74" },
    { "Level 75" },
    { "Level 76" },
    { "Level 77" },
    { "Level 78" },
    { "Level 79" },
    { "Level 80" },
    { "Level 81" },
    { "Level 82" },
    { "Level 83" },
    { "Level 84" },
    { "Level 85" },
    { "Level 86" },
    { "Level 87" },
    { "Level 88" },
    { "Level 89" },
    { "Level 90" },
    { "Level 91" },
    { "Level 92" },
    { "Level 93" },
    { "Level 94" },
    { "Level 95" },
    { "Level 96" },
    { "Level 97" },
    { "Level 98" },
    { "Level 99" },
    { "Valor level 2" },
    { "Valor level 3" },
    { "Valor level 4" },
    { "Valor level 5" },
    { "Valor level 6" },
    { "Valor level 7" },
    { "Wisdom level 2" },
    { "Wisdom level 3" },
    { "Wisdom level 4" },
    { "Wisdom level 5" },
    { "Wisdom level 6" },
    { "Wisdom level 7" },
    { "Limit level 2" },
    { "Limit level 3" },
    { "Limit level 4" },
    { "Limit level 5" },
    { "Limit level 6" },
    { "Limit level 7" },
    { "Master level 2" },
    { "Master level 3" },
    { "Master level 4" },
    { "Master level 5" },
    { "Master level 6" },
    { "Master level 7" },
    { "Final level 2" },
    { "Final level 3" },
    { "Final level 4" },
    { "Final level 5" },
    { "Final level 6" },
    { "Final level 7" },
    { "@Garden of Assemblage/(CoR) Garden of Assemblage Map/(CoR) Garden of Assemblage Map" },
    { "@Garden of Assemblage/(CoR) GoA Lost Illusion/(CoR) GoA Lost Illusion" },
    { "@Garden of Assemblage/(CoR) Proof of Nonexistence Location/(CoR) Proof of Nonexistence Location" },
    { "FAKE Slot" },
    { "Detection Saber Slot" },
    { "Edge of Ultima Slot" },
    { "Kingdom Key Slot" },
    { "Oathkeeper Slot" },
    { "Oblivion Slot" },
    { "Star Seeker Slot" },
    { "Hidden Dragon Slot" },
    { "Hero's Crest Slot" },
    { "Monochrome Slot" },
    { "Follow the Wind Slot" },
    { "Circle of Life Slot" },
    { "Photon Debugger Slot" },
    { "Gull Wing Slot" },
    { "Rumbling Rose Slot" },
    { "Guardian Soul Slot" },
    { "Wishing Lamp Slot" },
    { "Decisive Pumpkin Slot" },
    { "Sweet Memories Slot" },
    { "Mysterious Abyss Slot" },
    { "Sleeping Lion Slot" },
    { "Bond of Flame Slot" },
    { "Two Become One Slot" },
    { "Fatal Crest Slot" },
    { "Fenrir Slot" },
    { "Ultima Weapon Slot" },
    { "Winner's Proof Slot" },
    { "Pureblood Slot" },
    { "(SP) Screens Bonus: Donald Slot 1" },
    { "(HB2) Demyx Bonus: Donald Slot 1" },
    { "(OC) Demyx Bonus: Donald Slot 1" },
    { "(TR) Boat Pete Bonus: Donald Slot 1" },
    { "(TR) Boat Pete Bonus: Donald Slot 2" },
    { "(HT) Prison Keeper Bonus: Donald Slot 1" },
    { "(PL) Scar Bonus: Donald Slot 1" },
    { "(SP2) Solar Sailer Bonus: Donald Slot 1" },
    { "(HT2) Experiment Bonus: Donald Slot 1" },
    { "(PR) Boat Fight Bonus: Donald Slot 1" },
    { "(TT3) Mansion Nobodies Bonus: Donald Slot 1" },
    { "(BC) Thresholder Bonus: Donald Slot 1" },
    { "(BC2) Xaldin Bonus: Donald Slot 1" },
    { "(PR2) Grim Reaper 2 Bonus: Donald Slot 1" },
    { "Comet Staff Slot" },
    { "Hammer Staff Slot" },
    { "Lord's Broom Slot" },
    { "Mages Staff Slot" },
    { "Meteor Staff Slot" },
    { "Nobody Lance Slot" },
    { "Precious Mushroom Slot" },
    { "Precious Mushroom+ Slot" },
    { "Premium Mushroom Slot" },
    { "Rising Dragon Slot" },
    { "Save The Queen+ Slot" },
    { "Shaman's Relic Slot" },
    { "Victory Bell Slot" },
    { "Wisdom Wand Slot" },
    { "Centurion+ Slot" },
    { "(AG) Abu Escort Bonus: Donald Slot 1" },
    { "(PR) Barbossa Bonus: Goofy Slot 1" },
    { "(PR) Barbossa Bonus: Goofy Slot 2" },
    { "(PR2) Grim Reaper 1 Bonus: Goofy Slot 1" },
    { "(SP) Hostile Program Bonus: Goofy Slot 1" },
    { "(PL) Hyenas 1 Bonus: Goofy Slot 1" },
    { "(PL2) Hyenas 2 Bonus: Goofy Slot 1" },
    { "(HT2) Lock, Shock and Barrel Bonus: Goofy Slot 1" },
    { "(HT) Oogie Boogie Bonus: Goofy Slot 1" },
    { "(OC) Pete Bonus: Goofy Slot 1" },
    { "(TR) Future Pete Bonus: Goofy Slot 1" },
    { "(LoD) Shan-Yu Bonus: Goofy Slot 1" },
    { "(LoD2) Storm Rider Bonus: Goofy Slot 1" },
    { "(BC) Beast Bonus: Goofy Slot 1" },
    { "(PR) Interceptor Barrels Bonus: Goofy Slot 1" },
    { "(AG) Treasure Room Heartless Bonus: Goofy Slot 1" },
    { "Zexion Bonus: Goofy Slot 1" },
    { "Adamant Shield Slot" },
    { "Akashic Record Slot" },
    { "Chain Gear Slot" },
    { "Dream Cloud Slot" },
    { "Falling Star Slot" },
    { "Frozen Pride+ Slot" },
    { "Genji Shield Slot" },
    { "Knight Defender Slot" },
    { "Knight's Shield Slot" },
    { "Majestic Mushroom Slot" },
    { "Majestic Mushroom+ Slot" },
    { "Nobody Guard Slot" },
    { "Ogre Shield Slot" },
    { "Save The King+ Slot" },
    { "Ultimate Mushroom Slot" },
    { "(AT) Undersea Kingdom Map" },
    { "(AT) Mysterious Abyss" },
    { "(AT) Musical Blizzard Element" },
    { "(AT) Musical Orichalcum+" },
    { "Summon level 2" },
    { "Summon level 3" },
    { "Summon level 4" },
    { "Summon level 5" },
    { "Summon level 6" },
    { "Summon level 7" }
}

LOCATION_MAPPING = {}
for n, item in ipairs(LOCATIONS) do
    LOCATION_MAPPING[0x130000 + n - 1] = item
end
